name: Install and build
description: Install and build applications

inputs:
  NODE_AUTH_TOKEN:
    required: true

runs:
  using: composite
  steps: 
    - name: Use Node.js v16.14.2
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
        registry-url: https://npm.pkg.github.com
        cache: npm
        cache-dependency-path: '**/package-lock.json'
    
    - name: Get node-modules from cache
      id: node-modules-cache
      uses: actions/cache@v3
      with:
        path: |
          ./node_modules
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      uses: bahmutov/npm-install@v1
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
    
    - name: Initial Setup
      shell: bash
      run: ./_scripts/setup.sh

    - name: Get build bundles from cache
      id: build-cache
      uses: actions@cache@v3
      with:
        path: |
          **/dist
        key: ${{ runner.os }}-build-${{ github.sha }}
    
    - name: Build Application
      if: steps.build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm run build
